strange errors
2-27 22:03:01.821969190 UTC src/main.rs:254 sender  count=1
2020-02-27 22:03:01.821990701 UTC src/main.rs:225   tup=1  (b.timestamp-a.timestamp)=Duration { secs: 0, nanos: 181029 }  b.ptr[0]=Complex { re: 548.0, im: -1354.0 }
2020-02-27 22:03:01.822745546 UTC src/main.rs:254 sender  count=2
2020-02-27 22:03:01.822767546 UTC src/main.rs:225   tup=2  (b.timestamp-a.timestamp)=Duration { secs: 0, nanos: 182775 }  b.ptr[0]=Complex { re: -120.0, im: 2181.0 }
2020-02-27 22:03:01.823536359 UTC src/main.rs:254 sender  count=0
2020-02-27 22:03:01.823557870 UTC src/main.rs:225   tup=0  (b.timestamp-a.timestamp)=Duration { secs: 0, nanos: 188502 }  b.ptr[0]=Complex { re: -4436.0, im: -5589.0 }
thread 'main' panicked at 'rendering failed: BadTexture(TextureId(2))', src/main.rs:98:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2020-02-27 22:03:01.824337089 UTC src/main.rs:254 sender  count=1
2020-02-27 22:03:01.824359089 UTC src/main.rs:225   tup=1  (b.timestamp-a.timestamp)=Duration { secs: 0, nanos: 183124 }  b.ptr[0]=Complex { re: -3208.0, im: -637.0 }
thread 'pluto_reader' panicked at 'cannot access stdout during shutdown', src/libstd/io/stdio.rs:487:25

2020-02-27 22:02:17.437728321 UTC src/main.rs:225   tup=0  (b.timestamp-a.timestamp)=Duration { secs: 0, nanos: 188501 }  b.ptr[0]=Complex { re: 4012.0, im: 3801.0 }
2020-02-27 22:02:17.438509426 UTC src/main.rs:254 sender  count=1
2020-02-27 22:02:17.438535267 UTC src/main.rs:225   tup=1  (b.timestamp-a.timestamp)=Duration { secs: 0, nanos: 193042 }  b.ptr[0]=Complex { re: -3440.0, im: -111.0 }
thread 'pluto_reader' panicked at 'cannot access stdout during shutdown', src/libstd/io/stdio.rs:487:25
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_failed
             at src/libcore/option.rs:1203
  14: core::option::Option<T>::expect
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libcore/option.rs:347
  15: std::io::stdio::stdout
             at src/libstd/io/stdio.rs:487
  16: std::io::stdio::print_to::{{closure}}
             at src/libstd/io/stdio.rs:800
  17: std::thread::local::LocalKey<T>::try_with
             at src/libstd/thread/local.rs:262
  18: std::io::stdio::print_to
             at src/libstd/io/stdio.rs:793
  19: std::io::stdio::_print
             at src/libstd/io/stdio.rs:817
  20: adalm_pluto_viewer::main::{{closure}}::{{closure}}
             at src/main.rs:254
  21: crossbeam_utils::thread::scope::{{closure}}
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.7.2/src/thread.rs:161
  22: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panic.rs:318
  23: std::panicking::try::do_call
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panicking.rs:303
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  25: std::panicking::try
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panicking.rs:281
  26: std::panic::catch_unwind
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panic.rs:394
  27: crossbeam_utils::thread::scope
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.7.2/src/thread.rs:161
  28: adalm_pluto_viewer::main::{{closure}}
             at src/main.rs:207
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.